# Generated by Django 3.2 on 2023-01-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_alter_employees_dateofjoining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoining',
            field=models.DateField(),
        ),
    ]
